name: Flutter Web Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2

      - name: Build Flutter Web
        env:
          API_BASE_URL: ${{ vars.API_BASE_URL }}
          # or, if you used Secrets:
          # API_BASE_URL: ${{ secrets.API_BASE_URL }}
        run: |
          flutter build web \
            --release \
            --base-href /carman-frontend/ \
            --dart-define=API_BASE_URL=$API_BASE_URL

      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh-pages --force
